### ISSUE TITLE
A few issues with controls on this module

### ISSUE THREAD

**Issue by franckflo** [Saibot393/perceptive#1]
Hi, first I love the concept of this module so thanks for making it !

I am using FVTT 11.307 with DnD 5e system 2.3.1 and am hosting on Forge.

I believe your module conflicts with the Elevated Vision module. When both of them are enabled : 
- After making a door peekable, left-clicking on that door actually peeks through the keyhole and doesn't open it anymore. I believe it's supposed to be peeked through only on CTRL Right-Click as mentioned in your instructions.
- If I enable the door to be swingable or slidable, scrolling the mouse is typically used to zoom out/in so there is a conflict with opening the door. 

**In general and outside this conflict, it would be nice to have configurable hotkeys for this module, as for example mouse scrolling is typically used for zooming in and out of the canvas.**

Thanks a lot for looking into this!

**Comment by Saibot393** [comment]
Thanks for the bug report. I will look into the compatibility issues for the next update and also add the key bindings. 
Regarding your second point with the scrolling control of swinging/sliding doors: The module should disable canvas scrolling while hovering a door control, if that is not the case for you there is probably another compatibility issue besides Elevated Vision.

**Comment by franckflo** [comment]
Good to know, I'll run find the culprit for the scrolling issue and let you know if I find another module that could be conflicting.

**Comment by Saibot393** [comment]
I have added key support with v1.1.0. Solving the bug will take bit longer, i am currently waiting for the developer of the Elevated Vision module to reply.

**Comment by A7207** [comment]
Super quick note: I was having the same issue with the scroll wheel. For me, it ended up being "Zoom/Pan Options" https://github.com/shemetz/ZoomPanOptions

**Comment by Saibot393** [comment]
Thank you, i will look into it, maybe i can do something to improve compatibility.

**Comment by Saibot393** [comment]
I have just released v2.0.7 which should (if Zoom/Pan options truly was the compatibility issue) solve the problem with the mouse wheel. When hovering a door control the canvas should no longer zoom and the door should be moved instead.

**Comment by Saibot393** [comment]
I can no longer replicate any control bugs with any of the modules i tested it with. Unless i hear otherwise, i will assume this issue to be solved and close it soon
