### ISSUE TITLE
When interacting with door performance severly decrease

### ISSUE THREAD

**Issue by GorodZolotoy** [Saibot393/perceptive#10]
I don't know if this is a compatibility issue or not but whenever an actor interacts with a door Fvtt suffers from massive performance decrease. It appears to be creating multiple walls on the same spot as the door that is causing the performance decrease?

**Comment by GorodZolotoy** [comment]
<img width="152" alt="Screenshot 2023-09-18 082709" src="https://github.com/Saibot393/perceptive/assets/98506009/fc75954b-e435-4164-8517-71934ff363ed">
For interactions I mean opening and closing doors.

**Comment by Saibot393** [comment]
Also, do any error show up in the console(F12) when a player open a door, either for the gm or the player?

**Comment by GorodZolotoy** [comment]
I use better roof, level, wall height, monk's wall enhancement, and multilevel tokens.

One related error that I see is this:

Uncaught (in promise) TypeError: undefined. Cannot read properties of null (reading 'flags')
[Detected 1 package: perceptive]
    at WallUtils.deletewall (WallUtils.js:68:13)
    at PerceptiveFlags.deleteLockpeekingWalls (PerceptiveFlags.js:756:14)
    at PeekingManager.onDeleteWall (PeekingScript.js:143:25)
    at Object.fn (PeekingScript.js:215:18)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13759:13)
    at foundry.js:13734:43
    at Array.map (<anonymous>)
    at #handleDeleteDocuments (foundry.js:13734:33)
    at async WallDocument.deleteDocuments (commons.js:8011:23)

**Comment by GorodZolotoy** [comment]
This might not be a bug or a compatibility issue. It might just be due to my 4-level map's complexities making the recalculations of creating the walls take a real long time. Let me test it on another world.

**Comment by GorodZolotoy** [comment]
The performance is a bit better when it is utilized on a smaller map, I think its just my server unable to handle the processing necessary. Sorry for the bother.

**Comment by Saibot393** [comment]
No problem, i will still look into it, maybe i can do something about. At least the error is worth looking into.

**Comment by GorodZolotoy** [comment]
Just a quick question while I am at it. How do I utilize active perception with pf2e? It keeps on saying it doesnt detect any secret doors.

**Comment by Saibot393** [comment]
I just found a bug that caused hidden doors not to be actively spottable. The bug is fixed with v1.7.1. Thanks for notifying me.
