### ISSUE TITLE
Canvas freezes when I view token's vision as GM

### ISSUE THREAD

**Issue by dg1m** [Saibot393/perceptive#100]
I just updated to v12 and when Perceptive is active and I click on a token to preview its vision the canvas freezes. I have to change scenes to unfreeze. I don't have this issue with the Perceptive module disabled. Let me know if this is actually an issue with another module and I'll open an issue with them.

`Uncaught TypeError: pwall is undefined
[Detected 4 packages: perceptive, lib-wrapper, levels, system:pf2e]
    <anonymous> PerceptiveCompatibility.js:239
    call_wrapper libWrapper-wrapper.js:616
    shouldIgnoreWall#0 libWrapper-wrapper.js:189
    walls3dTest sightHandler.js:419
    testCollision sightHandler.js:342
    checkCollision sightHandler.js:501
    advancedLosTestInLos sightHandler.js:62
    advancedLosTestVisibility sightHandler.js:21
    performLOSTest sightHandler.js:15
    containsWrapper sightHandler.js:267
    call_wrapper libWrapper-wrapper.js:616
    contains#0 libWrapper-wrapper.js:189
    _testLOS foundry.js:51958
    _testPoint foundry.js:51926
    _testPoint foundry.js:52039
    testVisibility foundry.js:51878
    testVisibility foundry.js:51878
    testVisibility foundry.js:37631
    call_wrapped libWrapper-wrapper.js:507
    visibilityWrapper wrappers.js:102
    call_wrapper libWrapper-wrapper.js:616
    testVisibility#0 libWrapper-wrapper.js:189
    get isVisible pf2e.mjs:1370
    call_wrapped libWrapper-wrapper.js:507
    <anonymous> BasicPatches.js:142
    call_wrapper libWrapper-wrapper.js:616
    tokenUIWrapperIsVisible uiHandler.js:40
    call_wrapper libWrapper-wrapper.js:616
    isVisible#getter libWrapper-wrapper.js:364
    _refreshVisibility foundry.js:59317
    _refreshVisibility pf2e.mjs:1370
    _applyRenderFlags foundry.js:59268
    _applyRenderFlags pf2e.mjs:1370
    applyRenderFlags foundry.js:26348
    #applyRenderFlags foundry.js:25973
    emit TickerListener.ts:71
    update Ticker.ts:427
    _tick Ticker.ts:129
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
    _tick Ticker.ts:133
PerceptiveCompatibility.js:239:214
    <anonymous> PerceptiveCompatibility.js:239
    call_wrapper libWrapper-wrapper.js:616
    shouldIgnoreWall#0 libWrapper-wrapper.js:189
    walls3dTest sightHandler.js:419
    testCollision sightHandler.js:342
    checkCollision sightHandler.js:501
    advancedLosTestInLos sightHandler.js:62
    advancedLosTestVisibility sightHandler.js:21
    performLOSTest sightHandler.js:15
    containsWrapper sightHandler.js:267
    call_wrapper libWrapper-wrapper.js:616
    contains#0 libWrapper-wrapper.js:189
    _testLOS foundry.js:51958
    _testPoint foundry.js:51926
    _testPoint foundry.js:52039
    testVisibility foundry.js:51878
    some self-hosted:137
    testVisibility foundry.js:51878
    testVisibility foundry.js:37631
    call_wrapped libWrapper-wrapper.js:507
    visibilityWrapper wrappers.js:102
    call_wrapper libWrapper-wrapper.js:616
    testVisibility#0 libWrapper-wrapper.js:189
    get isVisible pf2e.mjs:1370
    call_wrapped libWrapper-wrapper.js:507
    <anonymous> BasicPatches.js:142
    call_wrapper libWrapper-wrapper.js:616
    tokenUIWrapperIsVisible uiHandler.js:40
    call_wrapper libWrapper-wrapper.js:616
    isVisible#getter libWrapper-wrapper.js:364
    _refreshVisibility foundry.js:59317
    _refreshVisibility pf2e.mjs:1370
    _applyRenderFlags foundry.js:59268
    _applyRenderFlags pf2e.mjs:1370
    applyRenderFlags foundry.js:26348
    #applyRenderFlags foundry.js:25973
    emit TickerListener.ts:71
    update Ticker.ts:427
    _tick Ticker.ts:129
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
    (Async: FrameRequestCallback)
    _tick Ticker.ts:133
`

**Comment by Saibot393** [comment]
The bug should now be fixed with v4.0.6
