### ISSUE TITLE
Perceptive stealth is not set when stealth check is rolled

### ISSUE THREAD

**Issue by TheXeno30** [Saibot393/perceptive#102]
![image](https://github.com/user-attachments/assets/d72e1c28-0621-4c29-aa21-bee44a0b9128)

Perceptive stealth is not set when stealth check is rolled - Can be spotted does.

Where am i going wrong with the settings :)

**Comment by Saibot393** [comment]
Assuming you have both the settings "Automate token can bespotted" and "Use perceptive stealthing" perceptive stealthing should be set automatically when rolling stealth. If that is not the case:
- Are there any errors in the console(F12)?
- Are any other modules activated and does the effect work as expected when those modules are turned of?
- What is the setting "Make spotted tokens visible" set to and is there any token in the test scene that could possible spot the test token?

**Comment by TheXeno30** [comment]
![image](https://github.com/user-attachments/assets/032f90b7-b71e-4bf2-b480-869782405e5b)
![image](https://github.com/user-attachments/assets/eef3b782-4a02-46cc-a8eb-71ee3df64aa1)

- Both   "Automate token can bespotted" and "Use perceptive stealthing" ia on 
- think it might be the Dfreds CE new effects
- "Make spotted tokens visible" is set to never

**Comment by Saibot393** [comment]
yes that seems like it could be the cause, i will look into a fix

**Comment by TheXeno30** [comment]
thanks for a very cool module btw - my rogue loves it. :)

**Comment by Saibot393** [comment]
happy to hear that

**Comment by TheXeno30** [comment]
that was quick - thanks.

**Comment by TheXeno30** [comment]
it works :)
But... don't know if it your module or vision 5e that controls the hearing.
When your are spotted by a token and you are in darkness the token should not be spotted with vision but with hearing.
![image](https://github.com/user-attachments/assets/c578b31b-eba3-4824-9151-1dddf9398a49)
![image](https://github.com/user-attachments/assets/392d10c4-60b1-40b2-a6c7-c62adb332254)
(The bandit has spottet the rogue)

**Comment by Saibot393** [comment]
Ah, yes, that is one of the things that is currently not possible/compatible with perceptive. I will look into adding that when i have a time, possible in combination with Vision 5e.

**Comment by TheXeno30** [comment]
Isn't Perceptive suppose to add a inaudiable and inviable CE to the token? It still hides the token correctly, but no CE

**Comment by Saibot393** [comment]
If the following settings are activate those effects should be added: 
"DFreds Convenient Effects Integration"
"Vision 5e Integration"
"Apply system stealth effect"

**Comment by TheXeno30** [comment]
all on but no CE effect or system effects
![image](https://github.com/user-attachments/assets/4aef1367-5743-4b7b-969a-6463c7e3a990)

**Comment by Saibot393** [comment]
Which versions of Foundry, D&D and DFreds CE are you using?

**Comment by TheXeno30** [comment]
V12.331, DnD 3.3.1, Dfreds 7.0.1

**Comment by Saibot393** [comment]
I completely missed that DFreds has a v12 compatible version now, something probably changed in the api, i will look into it.

**Comment by TheXeno30** [comment]
Came out yesterday 😂😂 so I think it’s ok not to know. Thank you for looking into it.

**Comment by Saibot393** [comment]
I have restored DFreds CE compatibility with v4.0.8. However, it seems like Vision 5e does no longer add the "Inaudible" effect to the DCE effects. Since i do not use Vision 5e myself i am not sure how the hearing system works now.

**Comment by TheXeno30** [comment]
thank you so much. Vision 5e (the most incorrect title ever :)) is working correctly, except as described above, but it doesn't add the inaudible effect anymore.

**Comment by Saibot393** [comment]
For the time being: I am not entirely sure if Vision 5e still interacts with effects that are simply called "Inaudible", if that is the case, adding an effect named "Inaudible" to the DCE effect folder will still cause Perceptive to add it (assuming the appropiate settings are activated)
