### ISSUE TITLE
Player controls and peeking not working

### ISSUE THREAD

**Issue by Twitchybait** [Saibot393/perceptive#104]
Running into two issues, I was able to use peeking when I first added this but recently it simply doesn't work anymore even when changing keybindings. Similarly my players have 0 control over slowly opening a door and retain only normal door controls (click to open) but the scroll to slowly open works fine as the gm.
I'm not sure if I'm missing a setting or if this is some sort of conflict with the newest version of foundry. Note I did disable all other modules just to make sure it wasn't a conflict.

**Comment by Saibot393** [comment]
Everything seems to work fine for me.
Were you logged in as a GM when a player was using those features?
Which foundry version are you using?
Which perceptive version are you using?
Do you have any other modules activated?
Which browser are you/your players using?
Could you send me a screenshot of your Lock Peeking and Door moving settings?

**Comment by Twitchybait** [comment]
-I was logged in as a GM with 5 players and none of them could get it to work but I could while playing as GM. I later (post session) attempted to log in as a player and check it and it didn't work while logged in as a player.
-There was one regarding a possible conflict with arms reach so I turned it off and then later tested it with no other modules on other than perceptive to ensure it wasn't a possible conflict.
-Foundry version 12 stable
-Perceptive version 4.08
-I did at the time, I have since turned off all other modules to check for conflicts but am experiencing the same thing.
-Opera GX
![image](https://github.com/user-attachments/assets/1f6cd19f-8603-4903-a7e0-0189c03d9e08)
![image](https://github.com/user-attachments/assets/3360b53d-474d-4c1a-a60e-16c59f731c7e)
![image](https://github.com/user-attachments/assets/7cf6b85a-0556-4bea-9216-d39f07d64503)

**Comment by Saibot393** [comment]
I still can not replicate the the bug.
-Which exact foundry version (331, newest?) are you using?
- Could you send me the .json export of a scene in which this bug occurs?

**Comment by Twitchybait** [comment]
Build 330, pf2e second edition 6.2.3 if that matters.
[fvtt-Scene-manor-grounds-w4slrtvHbeC00muZ.json](https://github.com/user-attachments/files/16806432/fvtt-Scene-manor-grounds-w4slrtvHbeC00muZ.json)
Drew a wall/door here to test for an upcoming game

**Comment by Saibot393** [comment]
I can sadly still not replicate the bug
- While having the perceptive client setting "Message Popups" and the foundry setting "Scrolling Status Text" enabled are there any popups while trying to move/peek a door as a player?
- What happens if you set the range in the settings to -1, does moving/peeking work then?
- Just to make sure, is the game unpaused while testing as a player?

**Comment by Twitchybait** [comment]
It started working, not sure if it was because I was logging out as the GM to log in as a player or what but when I had a player log in to test with me it worked fine now, no clue what changed lol but thanks for your time.

**Comment by Saibot393** [comment]
Good to hear that it is solved either way
