### ISSUE TITLE
[Bug] Console errors on load

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#12]
Using latest update, I get two console errors noted in the screenshot on load.
<img width="542" alt="Screenshot 2023-09-22 at 11 43 23 AM" src="https://github.com/Saibot393/perceptive/assets/90105219/74bb8bc4-b38e-4886-87ba-822a2c28d5bd">

**Comment by Saibot393** [comment]
I am suspecting, that this is some kind of compatibility issue. What other modules do you have installed, especially or wall related modules would be relevant. Also, what system are you using and does this error cause any other noticeable effects/bugs?

**Comment by weepingminotaur** [comment]
Well, the first error seems to be some kind of wrapping issue, but I'll check for module incompatibilities. I'm on Pf2e, latest system. So far, I've had weird results trying to get secret door detection working. Will follow up with more info.

**Comment by Saibot393** [comment]
My problem is, that the wrapper error does not really seem to make any sense to me since no other module is mentioned and the details given seem a bit nonsensical.

**Comment by Saibot393** [comment]
v1.8.2 could potentially fix this bug. If thats the case something very strange might be going on with another of your installed modules, namely that one of them is calling "init" twice. I would imagine that this could cause some other strange behaviour.

**Comment by weepingminotaur** [comment]
Updates seem to have fixed these errors. Thanks!

**Comment by weepingminotaur** [comment]
Also, testing in a blank world produces no errors, so evidently I have some module conflicts I need to FTC.

**Comment by Saibot393** [comment]
good to hear that the bug is fixed
