### ISSUE TITLE
[Bug] conflict with Stealth module

### ISSUE THREAD

**Issue by rinnocenti** [Saibot393/perceptive#13]
I'm having problems with the module in conjunction with the stealth module.
When selecting a token that tests vision it shows this error.

Foundry 11.309
DnD 5e
Stealth 3.13.2
Perceptive: 1.8.0

![image](https://github.com/Saibot393/perceptive/assets/3178127/394a02c8-82b3-48d6-8380-d91421e355b8)
![image](https://github.com/Saibot393/perceptive/assets/3178127/e637e8d4-70f8-41b9-b817-b54f4391f877)

**Comment by Saibot393** [comment]
Thanks for reporting the bug. It should be fixed with v1.8.1.
