### ISSUE TITLE
[Issue?] Chat message for spotting tokens never returns results even when you spot something

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#15]
Not sure if this is because I'm testing as GM, but in case it isn't: I set a wall to be spotted with an active Perception DC, then move a token into range of the wall and roll a Perception check. Even when the check beats the wall's DC (and the wall registers that the token has spotted it), the chat message always says: You were able to spot 0 secret doors.

**Comment by weepingminotaur** [comment]
This is in a blank Pf2e world on the Forge with no modules active except Perceptive, libwrapper, socketLib, and The Forge: More Awesomeness.

**Comment by Saibot393** [comment]
Thats strange, i will look into it, thanks for reporting it

**Comment by weepingminotaur** [comment]
Thanks! The ping function doesn't seem to be working for me either.

**Comment by Saibot393** [comment]
Both use very similar code so it's probably the same bug.

**Comment by Saibot393** [comment]
Both bugs should be fixed with the new v1.8.3
