### ISSUE TITLE
[Request] Different interaction distances for different activities

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#16]
It would be great to be able to set default interaction distances for each of the following categories: door peeking, door spotting (secret), door opening, and token spotting. While you normally would want opening to be limited to 5-6 feet of the door, peeking would need the token to be directly adjacent, and spotting (per Pf2e rules) would be "up to a 10-foot square adjacent to you." Similarly, spotting a token in Pf2e is either "a 30-foot cone or a 15-foot burst within line of sight."

Sorry to be logging all these tickets. I am intrigued and impressed by this module and want to start using it in my Pf2e campaign! :)

**Comment by Saibot393** [comment]
Adding different interactions distances shouldn't be a problem.
Don't worry about all the tickets, they are good suggestions/bug reports. I am happy to hear that you like the module.

**Comment by Saibot393** [comment]
I have implemented the different distances for lock peeking and door moving with v1.9.0. The distance for spotting will take a bit since it is a bit more tricky with the way i implemented the spotting feature.

**Comment by Saibot393** [comment]
Addendum: I though of a way, that is relatively easy to implement. Will probably do it tomorrow.

**Comment by weepingminotaur** [comment]
Amazing -- thank you for this work!

**Comment by Saibot393** [comment]
I have just added a spotting range with v1.9.1. I am not sure if can more complex ranges (cones and such) since that could be a major hit on the performance

**Comment by weepingminotaur** [comment]
Awesome, thank you. I wonder if cone/burst spotting could be just a macro to avoid performance hits?

**Comment by Saibot393** [comment]
I think i could add it to perception rolls, my main concern is passive perception. One way cones can be realised is by limiting the foundry vision of a token to a cone shape.

**Comment by weepingminotaur** [comment]
Gotcha. In Pf2e those cones or bursts are for encounters only, not exploration, and it costs an action("Seek"), so they shouldn't trigger passively anyway.

**Comment by Saibot393** [comment]
Ok, thats something that should be easy enought to implement.

**Comment by Saibot393** [comment]
I just added an additional cone range with v1.9.4 (the cone is set to 90°)
