### ISSUE TITLE
[Bug] Spotting walls seems to be broken on latest update

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#17]
Trying to test token spotting a secret door and it's not working, with or without Pf2e rules on. When the "player perspective" option is on, a token does not find a secret door even when the Perception check matches or exceeds the door's DC. The wall itself does not register that anyone has spotted it. 

Blank Pf2e world with nothing but Perceptive, libwrapper, socketlib, and Forge on.

**Comment by Saibot393** [comment]
There was a small oversight with actively spotting doors  while a spotting range was set. SHould be fixed with v1.9.2. Thanks for reporting.
