### ISSUE TITLE
[Bug] GM Confirm Spotting dialog not working

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#20]
This option doesn't appear to work at the moment. When toggled on, doors and tokens are still revealed automatically following the Perception check without the dialog appearing.

**Comment by Saibot393** [comment]
Were you logged in as a GM when making the roll? The popup only shows up when a player makes the roll. I can add a drop down menu for the bahaviour (no popup, player only, all rolls)

**Comment by weepingminotaur** [comment]
Ah, I was testing only as GM, didn't realize. My bad.

**Comment by Saibot393** [comment]
No problem. Adding an option for GMs to also use the confirm dialog for their own rolls is probably a good idea anyway.

**Comment by Saibot393** [comment]
The setting for the confirm dialog has been apended with v2.0.0 so that it can now also be set ot apply to GM made rolls
