### ISSUE TITLE
[Enhancement] Pf2e "passive" perception outside combat

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#21]
Just realized that during exploration mode, you should be able to roll a Perception check and have that roll be defined as your check while you (for example) move around a dungeon room searching for traps and secret doors outside of combat, with no time pressure. If you enter another room, the GM can call for you to make another Perception check, at which point the result of that second roll would become the new value for spotting secret things.

Perhaps a field added to the seeking token? Something like "current Search check"?

**Comment by Saibot393** [comment]
I was already planning on adding something like this. I am currently not sure how to make an ui that allows the gm to easily stop this rolled value from being used. Maybe a HUD button that a) show the current value and b) resets it when being clicked and is c) invisible when no value is currently used

**Comment by weepingminotaur** [comment]
Yeah, a HUD button would be good!

**Comment by Saibot393** [comment]
The new feature "Lingering active perception" has been added with v2.0.0
