### ISSUE TITLE
[Enhancement] Config keys

### ISSUE THREAD

**Issue by rinnocenti** [Saibot393/perceptive#25]
It would be interesting to be able to configure the set of keys to open the door.
What has happened is that it conflicts with other modules, mainly using the mouse wheel, which keeps activating the zoom.
The action of opening doors slowly always opens the doors with the alt key or with ctrl or shift, they all work with the mouse wheel, but this function is associated with other foundry and it is not possible to change it.

It would be interesting to always keep the "O" key for everything related to opening doors, so "O" peeks, and "O + Mouse wheel" gradually opens the door.

**Comment by Saibot393** [comment]
I will look into it. The problem with compatibility would be though, that i can probably not get other modules to "ignore" inputs made while e.g. o i pressed.

**Comment by rinnocenti** [comment]
If it is possible to change the keys, you can avoid conflicts. The worst thing is using the mouse wheel, because the system uses it (to zoom) and you cannot change it.
Unless your module can block zoom while the port is selected.
but I think just changing the keys will do the trick.

**Comment by Saibot393** [comment]
Perceptive should normally block the map zoom while hovering a door. There seems to be some compatibility issue with a module though, that prevents this block (i am currently suspecting the module Zoom/Pan Options)

**Comment by Saibot393** [comment]
I have just released v2.0.7 which should (if Zoom/Pan options truly was the compatibility issue) solve the problem with the mouse wheel. When hovering a door control the canvas should no longer zoom and the door should be moved instead.

**Comment by Saibot393** [comment]
I have just released v2.1.0 which allows users to configure the keys used for lock peeking when rightclicking and moving a door with the mouse wheel
