### ISSUE TITLE
[Enhancement] Macro to clear active perception roll from selected token

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#30]
A few times, I have had a player roll a Perception in exploration, then forgot that the value was still on while the PC moved to another room. Sometimes this resulted in a PC finding something they weren't supposed to find, usually because that initial roll was high and Perceptive was checking against that roll in the next room over, and so on.

To mitigate this happening, I'd love to have a macro bundled with Perceptive that simply resets active Perception on the selected tokens to 0. That way, I can clear the value when a token enters another location and the PC isn't actually using the Search activity.

**Comment by Spuznik** [comment]
Better would be that it only last for a specific time for the player. Also what is the range you have set I use only 15 for this and it prevented issues I was having.

**Comment by weepingminotaur** [comment]
Tying to time might be tricky. I prefer to just be able to clear active Perception on a selected token.

I have the range set to 10 feet. The issue is that if a character rolls a 30 on Perception while searching Room A, and finds stuff, then moves into Room B but doesn't Search that room (is doing another exploration activity), that character will still find things in Room B.

**Comment by Spuznik** [comment]
Found this.

![image](https://github.com/Saibot393/perceptive/assets/142272986/41d6b4e7-47a0-40e4-9040-3df5bf4cc877)


Looks like it might be the answer?

**Comment by weepingminotaur** [comment]
I always thought that setting applied to when the target (hidden thing) moves, to simulate a creature making a stealth check after being spotted and becoming hidden again?

Even if it applied to the seeker, not the spotter, it wouldn't work, because then active perception would reset upon *any* movement. Like you move one square in the same room and your active Perception roll disappears. That's why I'd prefer a macro that I can use as GM when I deem appropriate. Deciding when to ask for a new Perception check sometimes fall under GM fiat, at least in Pf2e.

**Comment by Saibot393** [comment]
Correct, the "Reset spotted on token movement" only resets by whom this token has been spotted. Adding macro or timer to reset the lingering perception shouldn't be a problem, i might also add a maximum distance based on the position of the token when it made the original roll.

**Comment by Saibot393** [comment]
I have added macros and world settings to limit the radius and the duration with v2.6.0
