### ISSUE TITLE
Add trigger for Passive/Active dectection

### ISSUE THREAD

**Issue by Spuznik** [Saibot393/perceptive#31]
I have tested and the passive and active perception works great but I have only one issue when you want to pass it off to perform other activities via automation like MATT.  It works fine for Tiles as these can be simply made visible. For tokens using Item Piles like chest it has the potential to do this, but only if you can add a trigger to the detection. This would allow for effects on tokens like this.

![chrome_xrfBUQY8ke](https://github.com/Saibot393/LocknKey/assets/142272986/aaa0cf50-b2a4-4698-948d-b5c0e3a3ce38)

Currently I use a tile and trigger a passive skill check, but your perceptive script would eliminate the need with a trigger. It would also then allow for disarm if passed off via a trigger for a on Perceptionclick trigger potentially.

**Comment by Saibot393** [comment]
Adding triggers for spotting shouldn't be a problem, i can basically copy and paste most of the lock and key code for this purpose.

**Comment by Spuznik** [comment]
I hoped it was going to be that simple.....AWESOME!!!!!!

**Comment by Saibot393** [comment]
I have added the MATT triggers with v2.6.0
