### ISSUE TITLE
[Enhancement] Chat messages for lingering AP removal

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#33]
Just so everyone knows what's happening, it would be great if the GM received a chat message when lingering AP is removed from a token, whether automatically through the radius or time options, or manually through the macros. And if a player owns the token, they should also be notified when lingering AP expires (or at least, we should have the option to toggle player notification). As always, thank you for everything you do. This is a wonderful module!

**Comment by Saibot393** [comment]
I have added a new world setting "GM recives info messages" with v2.6.1 which enables these messages for the GM.

**Comment by weepingminotaur** [comment]
The chat notification works great now! Would love it if players got the same whispered chat message so they become aware of when they've lost lingering AP.

**Comment by Saibot393** [comment]
I plan on releasing an update tomorrow (probably). I will include that in there.

**Comment by Saibot393** [comment]
I have added a client setting for this notification with v2.8.0 (notice, that only the player that applied the lingering active perception gets notified)
