### ISSUE TITLE
[Bug] Lingering AP radius doesn't seem to work 

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#34]
I set the Lingering AP Radius to 25 (25 feet, I assume), then dropped a token on a test scene well out of that range. Rolled a Perception check for the token, then moved that token out of the Radius. Even out of the radius, the token still discovered a secret door when it came within 10 feet of it (10 feet being the value I set for Spotting Range out of combat).

**Comment by weepingminotaur** [comment]
The remove lingering AP macros don't seem to work either. I selected a token and used a macro, then moved it into range of a secret door with an active Perception DC, and it still found the door.

**Comment by Saibot393** [comment]
Does the gained/removed lingering lingering active perception popup show up (if enabled)? (the popup currently has a bug that causes it not to translate properly, will be fixed shortly). Also, does the lingering active perception indicator (bottom left in screenshot) show up after moving (if enabled)?
![image](https://github.com/Saibot393/perceptive/assets/137942782/b91ee5e0-0ff3-4093-a70e-9c1c968bac76)

**Comment by weepingminotaur** [comment]
Oh damn, didn't even notice the indicator, I will check! And I didn't have the popup enabled the first time, will also check that.

**Comment by weepingminotaur** [comment]
Ah, interesting. So the indicator does reset when the token moves outside the radius. Now I'll check with a secret door (I'd had the indicator off before on account of forgetting it even existed, lol).

**Comment by weepingminotaur** [comment]
OK, cool, so the error I initially mentioned only seems to happen if the indicator is set to not display. When the indicator is on, it seems to work fine. Thanks for helping me with this!

**Comment by Saibot393** [comment]
Thats strange, i will look into it.

**Comment by weepingminotaur** [comment]
Oh, and when the indicator is off, the chat message doesn't display to the GM about discovering secret things. Just tested that out and now I'm receiving GM notifications (with the indicator on).

**Comment by Saibot393** [comment]
Ok, its getting stranger

**Comment by Saibot393** [comment]
Did any errors show up in the console previously, when the active perception wasn't removed?

**Comment by weepingminotaur** [comment]
None that I could see (I checked the console).

**Comment by Saibot393** [comment]
I have just released v2.6.1 which makes a few small changes to lingering active perception. (They are unlikely to resolve this issue but i couldn't replicate this behaviour so this is my best guess for now, i will do a few more tests to see if there is a specific setting responsible)

**Comment by Saibot393** [comment]
I have added a debug mode with v2.6.3 (can be activated with `CONFIG.debug.perceptive.SpottingScript = true`), can you turn this on and send me the console output (starting with `perceptive:`), maybe i can see what prevent the lingering perception from being removed

**Comment by Saibot393** [comment]
There is a small chance, that v2.6.4 fixed this bug

**Comment by Saibot393** [comment]
The lingering active perception radius seems to be working reliable for me. Unless otherwise reported, i will close this issue soon.

**Comment by weepingminotaur** [comment]
Yep, it's working fine now!
