### ISSUE TITLE
Perceptive Triggers on Tokens failing to run

### ISSUE THREAD

**Issue by Spuznik** [Saibot393/perceptive#36]
When configuring a trigger using the Newly spotted trigger condition, they only work on Doors and Tiles. 
All attempts to get the Token to use the MATT trigger fails.

![image](https://github.com/Saibot393/perceptive/assets/142272986/719d410e-8926-4648-bf8c-406412ee79de)

![image](https://github.com/Saibot393/perceptive/assets/142272986/1984bf24-e960-4e3b-8d06-3b0f9276c197)

![image](https://github.com/Saibot393/perceptive/assets/142272986/d9eaafa9-d3a4-42d4-8d05-2b08691f790d)

![image](https://github.com/Saibot393/perceptive/assets/142272986/c7983341-964e-467f-8940-cf1e6130c1d4)

**Comment by Saibot393** [comment]
You seem to be using "Trapdetected" as the tile id, Perceptive expects the tile id you can copy when clicking the small icon at the top left of the tile windows:
![image](https://github.com/Saibot393/perceptive/assets/137942782/0c743875-8938-41c2-9bb8-521c1b7dc4ac)

**Comment by Spuznik** [comment]
I will retest now. Note that it worked for the Door using the same format TrapDetected, but that lets me select it.

**Comment by Spuznik** [comment]
Using the Tile ID doesn't make a difference. Sorry.

**Comment by Saibot393** [comment]
Was the token invisible before being spotted, i.e. was it already spotted before the active check either through passive perception or an active check?

**Comment by Saibot393** [comment]
Could you try to execute this in the console: `canvas.tiles.get("#Tileid").document.trigger({tokens:canvas.tokens.controlled.map(v=>v.document), method : "trigger", options : {landing : "ActiveSpot"}});` , replacing #Tileid with the id of the tile you want to trigger, while having the token selected you used for spotting

**Comment by Spuznik** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'document')
    at <anonymous>:3:65
(anonymous) @ VM117013:3

Note that if I then select the token it is meant to update it continues the script.

**Comment by Spuznik** [comment]
![msedge_3pOeG1b56a](https://github.com/Saibot393/perceptive/assets/142272986/999594a8-cd53-4018-80bc-5153751b8c55)

**Comment by Saibot393** [comment]
Perceptive can currently only trigger tiles in the same scene and therefore only accepts in scene ids, could you try using only the tile part of the id: `#Tileid` instead of `Scene.#Sceneid.Tile.#Tileid`

**Comment by Spuznik** [comment]
Yes this works with the tile id only.

**Comment by Saibot393** [comment]
I was honestly not even aware that tiles could be named, i guess thats a MATT feature i havent found yet?
