### ISSUE TITLE
AEs for advantage on hidden door checks

### ISSUE THREAD

**Issue by txm3278** [Saibot393/perceptive#37]
I'm currently trying to automate the first bullet on the [dungeon delver feat](https://www.dndbeyond.com/feats/dungeon-delver). I do not believe perceptive currently has options for this.

**Comment by Saibot393** [comment]
This is, funnily enough the next point on my to do list. I will probably be able to finish that tomorrow. The update will probably include syntax for AEs to add advantage/disadvantage/mali/boni for checks against specific entity types (doors, tokens, tiles).

**Comment by Saibot393** [comment]
I have released v2.7.0 which adds syntac for AE to affect the modifiers/roll behaviours described above. For dungeon delver the syntax should be:
- `flags.perceptive.Modifiers.perception.BEH.Wall.active` with value 1 for the first part
- `flags.perceptive.Modifiers.perception.BEH.Wall.inv` with value 1 for the second part
