### ISSUE TITLE
[Enhancement] Distance penalty

### ISSUE THREAD

**Issue by gurgugnao** [Saibot393/perceptive#38]
Hello! Very nice module!

It is feasible to introduce an option that add in the algorithm a penalty to the Perception check based on the distance of the spotter from the hidden creature? Like it was in D&D 3.5, where every 10 feet of distance you have a -1 penalty to Listen/Spot checks. This would be also interesting for hidden doors. The penalty to passive or active Perception should be X = distance in feet/10.

Thanks!

**Comment by Saibot393** [comment]
That should be no problem. I will look into it for the next update.

**Comment by Saibot393** [comment]
The world setting Range perception DC modifier has been added with v2.8.0 for this purpose
