### ISSUE TITLE
[Enhancement] Option to automatically remove lingering AP from PC tokens when combat is started

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#39]
Pretty much what it says. In Pf2e combat, all Perception checks need to be made through the provided macros (15-foot burst or 30-foot cone), and a check costs an action, so lingering AP should be removed. Ideally with a chat message reminding all players that lingering AP is gone.

**Comment by Saibot393** [comment]
I will include an option for that in the next update.

**Comment by Saibot393** [comment]
With v2.8.0 the lingering active perception will now be automatcally be removed at the start of combat, should should Active perception lingers be set to out of combat
