### ISSUE TITLE
[Feature request] Ambient sounds for open/close doors

### ISSUE THREAD

**Issue by Fridan99** [Saibot393/perceptive#40]
I have seen that the module works with doors. Now that the ambient doors (https://github.com/EndlesNights/ambientdoors) module is abandoned, you may want to add sounds to the doors (when it opens and closes).

Just a suggestion.

**Comment by weepingminotaur** [comment]
Door sounds have been core since v11. However being able to automatically set door sounds for all doors by default (and then custom sounds per door if needed) would be awesome.

**Comment by Fridan99** [comment]
Nice 🤣 good to read. I didn't know that the doors had sound since v11. But at least I guess not automatically, right? Since I deactivated ambient doors I can't hear them anymore.

**Comment by weepingminotaur** [comment]
Yeah, it's not automatic, you have to choose a sound for each door.

**Comment by Fridan99** [comment]
omg, core should have default sounds... that's a bit cumbersome, having to configure the sound for each door :P.... there's the copy/paste option, but it's still a bit arduous.

**Comment by Saibot393** [comment]
That is actually something that has bothered me aswell in the past, i think i will add an optional "Default door sound" setting to [Lock & Key](https://foundryvtt.com/packages/locknkey), i think it fits better there and i already have the code there

**Comment by Saibot393** [comment]
In the meaintime, here is a macro to change all door sounds in the current scene. Might be usefull:
```
let vSound = "woodBasic"; //change door sound here

let vDoors = canvas.walls.doors.map(vObject => vObject.document)

vDoors.forEach(vDoor => vDoor.update({doorSound : vSound })) 

```

**Comment by Saibot393** [comment]
Lock & Key v2.0.0 adds a world setting for the default sound
