### ISSUE TITLE
[Enhancement] Ability to adjust volume of spotted sound

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#41]
Depending on the audio file chosen, it could be too loud to have sounds triggering if we can't set the volume for the sound.

I love the spotted sound feature, by the way!

**Comment by Saibot393** [comment]
I will add an audio slider with the next update, a "test audio" button would also probably be usefull.

**Comment by Saibot393** [comment]
I have added a volume slider and a test sound button with v2.9.0
