### ISSUE TITLE
[Request] Door Peeking GM only

### ISSUE THREAD

**Issue by maxobremer** [Saibot393/perceptive#42]
It would be nice if you could set it so only the GM can set a token/actor to peek through a door. Sometimes I want players to roll perception before allowing them to get that information.

In addition, it might also be nice if you could link it to a DC and then also have a default DC that can be adjusted.

another way to go about it, maybe a keybind to quickly toggle if a door is peekable?

Thanks for the nice module so far btw

**Comment by Saibot393** [comment]
All of those should be relatively easy to do. I will add options for that with the next update.

**Comment by Saibot393** [comment]
In the meantime, here is a macro to toggle the peeakability of the hovered door:
```
vDoor = canvas.walls.hover?.document;

if (vDoor) {
    let vTargetState = !vDoor.flags?.perceptive?.canbeLockpeekedFlag;

    vDoor.update({flags : {perceptive : {canbeLockpeekedFlag : vTargetState}}});
}
```

**Comment by Saibot393** [comment]
I have added both a setting so that GMs have to confirm every peek "request" and an optional DC system  for peeking with v2.9.0
