### ISSUE TITLE
[Issue] Blank chat notifications with auto-remove lingering AP feature

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#44]
With Active Perception set to linger "Out of combat" and Notify on Lingering AP removal set to On, adding tokens to the combat tracker sends blank notifications for each token if the token does not have an AP value stored on it (i.e. if its active perception has already been removed manually or due to movement).

Would it be possible for Perceptive to check whether a token has active perception on it before sending that chat notification? That way, it could either not send a chat notification if the token doesn't have active perception to remove, or it could send a notification saying something like, "No active perception to remove for [token X]."

**Comment by Saibot393** [comment]
Thats an oversight, i will fix it with the next release.

**Comment by Saibot393** [comment]
Should be fixed with v2.8.3
