### ISSUE TITLE
[Enhancement] Flavour text when something is spotted

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#45]
Would be sweet to have a small text field on each element (door, token, loot, etc.) where you could input flavour text that would be posted to chat to the discovering player when they spot the element in question. "When you touch the hinge of the wardrobe, it swings open to reveal a portal." That kind of thing.

**Comment by Saibot393** [comment]
I will look into it for the next update, should be relatively easy to add.

**Comment by Saibot393** [comment]
I have added the flavour text with v2.9.0
