### ISSUE TITLE
[Issue] Stretched image in spotted notifications

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#47]
Not sure why this is happening, but all of a sudden I'm getting very stretched token images in the chat notification for lingering AP being removed. Screenshot attached.
<img width="305" alt="Screenshot 2023-11-17 at 10 10 46 PM" src="https://github.com/Saibot393/perceptive/assets/90105219/ff499c95-0392-473d-b534-6b4b9fc268dd">

**Comment by Saibot393** [comment]
I  can not replicate this bug, which ui modules are you using?

**Comment by weepingminotaur** [comment]
Dorako UI. My settings haven't changed, though. I'll keep digging to see if another module is doing something weird.

**Comment by weepingminotaur** [comment]
Find the Culprit has narrowed it down to a conflict with Pf2e Action Support Engine. I'll contact the dev for that.

**Comment by Saibot393** [comment]
I will also look into it, there may be something i can do about that

**Comment by Saibot393** [comment]
There is a small chance, that v2.9.1 fixes this bug

**Comment by weepingminotaur** [comment]
Awesome. And the Action Support Engine dev says it will be fixed in his next release.

**Comment by weepingminotaur** [comment]
Just checked with 2.9.1 and the stretched image is still there. I'll keep you posted when ASE gets an update and I can check again.

**Comment by Saibot393** [comment]
Is this still happening?

**Comment by weepingminotaur** [comment]
Nope, fixed!
