### ISSUE TITLE
[Compatibility issue] Wall Height

### ISSUE THREAD

**Issue by Kaaresandfaer** [Saibot393/perceptive#5]
sometimes when using this mod together with wall height, when peaking through the lock it will instead for a frame, show it as if the door was fully open.

**Comment by Saibot393** [comment]
Thanks for letting me know, i will look into it.

**Comment by Saibot393** [comment]
I have just released v1.4.0 which should improve upon/fix this bug. Since it is a bit of an illusive bug though, i can not guarantee that it is fixed completely, should it show up again, feel free to reopen this issue or open a new one.
