### ISSUE TITLE
[[Possible Bug]] Vision Channels

### ISSUE THREAD

**Issue by RinVindor** [Saibot393/perceptive#50]
So not sure if this is actually a bug or not but if a token has two Vision Channels and both of those VCs are toggled as Required to see, then even if a token can receive one of the VCs, because it cannot see the other the token is rendered invisible. Not sure if this is meant to be the case or not.

![image](https://github.com/Saibot393/perceptive/assets/12647469/c0266347-82f0-45a7-98b4-3f30e60e549b)

![image](https://github.com/Saibot393/perceptive/assets/12647469/3c9c1005-a5ac-4159-8a24-c0d25aad611b)

![image](https://github.com/Saibot393/perceptive/assets/12647469/716819ad-2507-4c51-92c8-4ff0d61c533b)

**Comment by Saibot393** [comment]
That is intended behaviour, the required channels operate on a logical "and" base. I can, should that be of use, add a world option though to toggle this into a logical "or" i.e. onlly one required channel is necessary

**Comment by Saibot393** [comment]
What exactly would you like normal sight to do? Also, from my interpretation of the way you want "Blood Scent" to work, i don't think you need "Required to see" here. The "Required to see" option is intended for thinks like an ethereal vision in D&D5e where you would need this sense to percive certain ghostly creatures.

**Comment by RinVindor** [comment]
Out of curiosity, its been a few weeks since we spoke prior but you can't stack vision channels correct? As in one is outlines and waves while another is say glow and be able to see them both simultaneously correct?

**Comment by Saibot393** [comment]
No, currently not. I am basically using the normal Foundry vision effect "slot" for the effects which only allows for one effect at a time. I might be able to make mixing possible in the future but that will require rewriting some of the render logic (when i do this, effects will also be applicable to tiles).
Btw. sorry for the long wait, i am still planning on adding the "or" logic feature i promissed. Thing is, that that will require me goind through the method at the core of vision channels and reqriting some relatively complex stuff, so i want to do this when i have a lots of time to do it right and not introduce some ugly bugs.

**Comment by RinVindor** [comment]
Hey no worries! I suspected as much that without a rewrite it wouldn't be possible atm. Take your time and thanks for the awesome work so far!

**Comment by Saibot393** [comment]
I finally got around to adding the logical OR mode with v3.2.0, sorry that it took so long
