### ISSUE TITLE
Tile color/tint missing

### ISSUE THREAD

**Issue by Ikabodo** [Saibot393/perceptive#53]
The latest update (or probably the one that added vision channels) have added a strange behavior with tile color.

![image](https://github.com/Saibot393/perceptive/assets/7766890/e8fecaf7-2546-4225-8d65-6b5cbfbffa0c)
This is a white tile, colored red.
![image](https://github.com/Saibot393/perceptive/assets/7766890/0bf2c197-09e5-4e5d-84d4-113b0e739671)

![image](https://github.com/Saibot393/perceptive/assets/7766890/3ffafcf2-9169-42e2-8414-5fc7a6db1739)
This is the same tile with a token selected.
Interestingly the tint remains "lost" until you reset a layer. For example if you click the tile layer and then BACK to the token layer again it is back to red. But as soon as you select a token again it's white again.

The screenshots are with modules. But this happens the same with only Perceptive active.

**Comment by Saibot393** [comment]
Should be fixed with v3.1.2
