### ISSUE TITLE
[PF2E] Issue with flickering when opening doors

### ISSUE THREAD

**Issue by Joshmvii7** [Saibot393/perceptive#54]
With Perceptive on, I get a flicker when doors are opened. Most of the time it's harmless but in our last session it was actually sometimes not letting the character's vision pass through, so they'd open a door but not see past it, and if they tried to move into the open door they'd be blocked as though it wasn't open. 

The only setting I have turned on is Spotting Invisible, but the issue persists regardless of which settings i toggle on and only stops when I deactivate Perceptive.

https://github.com/Saibot393/perceptive/assets/99048395/81c82ad2-6138-45d2-8ba8-7ff7f8b247c9

**Comment by Saibot393** [comment]
I will look into it.

**Comment by Joshmvii7** [comment]
Thank you. Some additional context I didn't include initially
Foundry: 11.315
Pathfinder 2E: 5.10.5
Browers: Both Edge and Chrome.

**Comment by Saibot393** [comment]
I did a bit of testing and i think i can replicate the behaviour. Just to confirm that we are have the same bug: The flickering only happens with doors taht have the setting "Door movement type" set to something other than "No movement", is that also the case for you?

**Comment by Joshmvii7** [comment]
Just checked, and yes, that's the same for me.

**Comment by Saibot393** [comment]
Then i almost got a fix for that, i still need to do some bug fixing and testing though, will release it tomorrow
