### ISSUE TITLE
Investigation Not showing "Spotting message" until after refresh

### ISSUE THREAD

**Issue by Geektasticdad** [Saibot393/perceptive#59]
Hello, running into some odd behavior, currently running the following: 

- Foundry: 11.315
- DnD5e - Fifth Edition System: 2.4.1
- Perceptive module: 3.1.9
- OS: Ubuntu 22.04.3 LTS

I'm trying to use the Perceptive module for an investigation check within range of a locked door that will display a message "You found a trap on this door."

I have "Can be spotted" enabled but I have left passive/active perception disabled. 
![image](https://github.com/Saibot393/perceptive/assets/73676044/73c1627b-b373-467a-bfb8-f1857dcef1aa)

In the Other active skill DCs I have set the Investigation DC to 10
![image](https://github.com/Saibot393/perceptive/assets/73676044/e73c9b29-7bdb-4f5c-a8cb-fac355b2757f)

Using a test user/actor I roll investigation that exceeds the DC but the message doesn't appear
![image](https://github.com/Saibot393/perceptive/assets/73676044/092e8cc1-f136-4680-9531-f69828965597)

But it does show that the character has spotted successfully
![image](https://github.com/Saibot393/perceptive/assets/73676044/1dd82daa-59d3-4b17-b01f-51e612299303)

HOWEVER, if I reload the browser on either the player or GM side, the message appears after Perceptive initializes
![image](https://github.com/Saibot393/perceptive/assets/73676044/f194bb21-38d2-4b4b-bbfb-51e4bbf7bbc5)

I see no errors before or after the refresh in the console, so not sure that will be much help but I do see the ChatMessage on both sides after I refresh (but not before).

**Comment by Saibot393** [comment]
This was actually never a use case i considered but it should now work with v3.1.10.
