### ISSUE TITLE
Loading any scene spams delete/create logs in console (Performance)

### ISSUE THREAD

**Issue by xKillerbees** [Saibot393/perceptive#60]
Module Version 3.1.11
Abomination Vaults official module

When I switch any scenes with walls/doors in it, I see trigger events that come from perceptive that delete and recreate all walls in the scene even if in the same session I was already in that scene. When it happens in a bigger scene, I can't even open character sheets or windows until it is complete due to the lag.

I believe one the last 2-3 updates has caused this. It's caused by the "door standard movement type" being set to swinging or sliding. 

And doors already opened will show open in the icon but I don't have vision through them without closing and reopening the door each load of the scene. 

![image](https://github.com/Saibot393/perceptive/assets/2941079/41e37643-b932-4f66-800b-854efa6b42fa)

**Comment by Saibot393** [comment]
Yes, i added that in a previous update to prevent possible bugs that could happen via lag or module incompatibility, i will look into it and see if i can find a more performant solution

**Comment by Saibot393** [comment]
The performance on sceneload should now be improved with v3.1.12, at least on previously loaded scenes.
