### ISSUE TITLE
Unable To Open Doors Or Peek Through Locks

### ISSUE THREAD

**Issue by DiceAndEasy** [Saibot393/perceptive#61]
I am unable to open doors by sliding them as the door will only open slightly and then close up again. Some times when I try to slide the door open, it will open towards the token and create a wall blocking vision. When I try to peek through a lock, the door icon changes to open but nothing else happens and if I try to keep peeking, the door icon will disappear. I've attached two videos of the issue to this ticket.

Foundry version: 11.315
Module version: 3.1.12
Platform: The Forge
Browser: Chrome

https://github.com/Saibot393/perceptive/assets/86520580/1dadc6b1-3870-4a81-8957-c334afa6c54b
https://github.com/Saibot393/perceptive/assets/86520580/7bd01034-7a75-45ac-8e0f-c1c9bbaea78a

**Comment by Saibot393** [comment]
The bug should be fixed with v3.1.13. The first time you load a scene with that bug you might need to have the new debug setting "Recreate Perceptive walls on scene load" to make sure, that everything works correctly.

**Comment by DiceAndEasy** [comment]
Moving walls issue fixed and now opening doors works as intended.

I was using the wrong button combo earlier for peeking through locks so that was my mistake. Lock peeking working as intended now.

Thanks for the update!

**Comment by Saibot393** [comment]
Good to hear
