### ISSUE TITLE
Bug ? Door fully open when scrolling down to close it

### ISSUE THREAD

**Issue by uniwars** [Saibot393/perceptive#62]
Hi, I just installed the module and test it and found out what I think may be an issue :

When a player slowly open a door by scrolling up and then close it by scrolling down fast the door will close and then fully open itself without me left clicking.

**Comment by Saibot393** [comment]
That might be a desynch problem, i will look into it.

**Comment by uniwars** [comment]
(I'm testing with two browser tab one for gm and one for player) I will try to find someone to test

**Comment by Saibot393** [comment]
The bug should be fixed with v3.1.14
