### ISSUE TITLE
[Bug] Players can't scroll to open doors

### ISSUE THREAD

**Issue by txm3278** [Saibot393/perceptive#7]
As a dm I am able to scroll to open a door but when my players try to nothing happens. There are no errors/warnings in console for me or my players when they attempt to

**Comment by Saibot393** [comment]
Could you send me a Screenshot of the error?

**Comment by txm3278** [comment]
I don't get any errors on the dm side or the player side. It just doesn't do anything for them. It does stop the canvas from zooming though

**Comment by Saibot393** [comment]
Sorry misread that, can you send me screen shot of the doors setting. Also, did you make sure, that the players token is within the set interaction distance?

**Comment by txm3278** [comment]
This might be a module conflict. I will run Find the Culprit before getting back to you

**Comment by txm3278** [comment]
The issue is with the arms reach setting. The player is within the range of the door to open it but it stops the door from scrolling open

**Comment by txm3278** [comment]
This happens as long as the arms reach option is selected. I set arms reach to use 10 which is perceptive's default and it still doesn't work but the 10 does work without arms reach

**Comment by Saibot393** [comment]
Just released v1.4.2 which should fix that bug

**Comment by txm3278** [comment]
Thanks for being so responsive on these! It is working now
