### ISSUE TITLE
[Bug] Successful spot check doesn't reduce Undetected to Hidden

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#71]
An Undetected creature successfully spotted by another creature seems to remain Undetected, rather than becoming Hidden.

**Comment by Saibot393** [comment]
I will look into it

**Comment by Saibot393** [comment]
Everything seems to work fine on my end, do you have the setting "Make spotted tokens visible" activated?

**Comment by weepingminotaur** [comment]
Yes, I do. I will double-check this issue again.

**Comment by Saibot393** [comment]
Don't worry, perceptive is at a point where i sometimes think i encountered a bug and it turns out that i simply forgot to change a setting
