### ISSUE TITLE
[Bug] Stealth DC not always calculated correctly for Pf2e monsters

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#72]
Using creatures like Shadow, Specter, and others, the stealth DC (active perception DC) isn't always calculated correctly. Sometimes it appears to only be taking the stealth modifier without adding the base 10. And modifying a token's stealth mod on the fly doesn't seem to adjust the active perception DC accordingly.

**Comment by Saibot393** [comment]
i will look into it

**Comment by Saibot393** [comment]
Will be fixed with the next version. I forgot, that NPCs have a slightly different skill DC path then players. The DC is only updates on a token update, so when changing the value you might need to move the token before the DC gets updated to the correct value

**Comment by Saibot393** [comment]
Should now be fixed with v3.2.2
