### ISSUE TITLE
Remove VC Macro Not "Saving" Or Applying To Player Account

### ISSUE THREAD

**Issue by EMPFingers** [Saibot393/perceptive#75]
Foundry build 315 V11
PF2E 5.13.6
Perceptive 3.3.0
Only Perceptive and Find the Culprit enabled.

Adding VC via add macro works properly and reveals the creature emitting.
![image](https://github.com/Saibot393/perceptive/assets/70672700/7b8c76a6-4174-4042-a228-759c82ea152b)

Removing VC via remove macro hides the enemy and removes the VC receiving correctly when applied as GM. However, this does not immediately update the player client's vision. The NPC emitter is still visible.
![image](https://github.com/Saibot393/perceptive/assets/70672700/38ea05f6-545f-4bc5-bf2f-d0becd8b4989)

Moving the player token adds the VC back to the token's receiving and immediately re reveals the token.
![image](https://github.com/Saibot393/perceptive/assets/70672700/7d857a67-b0f8-4b88-bf36-ed05638d1466)

Needs to be able to update on player client side when VC is removed and not add Receives back in when token moves. Please let me know if you need any additional information.

**Comment by Saibot393** [comment]
The bug with the vision channel not being removed/being readded when moving should be solved with v3.3.1 and the vision now corretly updates when the vision channels change.
