### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ExileofBrokenSky** [Saibot393/perceptive#76]
There is some MATT intergration already existing, I'd like to ask for some more :)
A MATT action that will clear all spotted-by lists on a given entity or entity tag.
If something similar already exists please let me know.

**Comment by Saibot393** [comment]
I already planned on adding more MATT actions, i will look into it soon

**Comment by Saibot393** [comment]
I have added the MATT action `Reset \"spotted by\"` (and few others) with v3.4.0
