### ISSUE TITLE
Prompt the GM about revealing tokens and walls

### ISSUE THREAD

**Issue by MrVauxs** [Saibot393/perceptive#8]
Lovely module, tried it out and works on the PF2e system. However, there is small issue. The module automatically reveals everything to a token once it rolls a Perception check, even if that perception check wasn't aimed towards revealing hidden tokens or walls, like Initiative.

My suggestion is to, by default, _prompt_ the GM about what is going to be revealed to a player _prior_ to making it visible to them.
This can save a lot of headaches on any system, including 5e, and GMs wont have to worry about tip-toeing around rolling Perception and the module revealing stuff it should not.

I think this system-agnostic solution is better than making the module explicitly have to support certain systems, especially when the rules would have to include stuff like checking if a wall or token is inside of a template portraying where the player is looking. And probably still have to make a prompt to the GM asking what has been seen and what has not been.

**Comment by Saibot393** [comment]
Thanks for the suggestion i will look into a popup prompt for the next version. For now there is a configurable key (alt by default) that a player can press while rolling to not let their roll count as a stealth/perception roll for the module. I will probably also add a client setting that lets players invert that button, so that only rolls that are mady _while_ holding the button count for the module.

**Comment by MrVauxs** [comment]
> Thanks for the suggestion i will look into a popup prompt for the next version. For now there is a configurable key (alt by default) that a player can press while rolling to not let their roll count as a stealth/perception roll for the module. I will probably also add a client setting that lets players invert that button, so that only rolls that are mady _while_ holding the button count for the module.

Lovely. However I think this should be inverted by default. For something that can automatically spoil GMs plans, the action to do so should be _**explicitly deliberate**_.

**Comment by Saibot393** [comment]
I have added the invert button with v1.5.1.
I can see how the standard behaviour could be a problem or annoying in some cases, though a potential problem with inverting the key by default is, that it could cause a bit of a confusion for new users that install the module and expect it to just work without looking further into the settings.
I will probably be able to implement the GM prompt this weekend at which point this shouldn't be much of problem anyway.

**Comment by MrVauxs** [comment]
> I have added the invert button with v1.5.1.
> I can see how the standard behaviour could be a problem or annoying in some cases, though a potential problem with inverting the key by default is, that it could cause a bit of a confusion for new users that install the module and expect it to just work without looking further into the settings.
> I will probably be able to implement the GM prompt this weekend at which point this shouldn't be much of problem anyway.

I think it's worth inverting that setting by default as opposed to having the GM have to use another module to force that client setting onto the players. I can imagine people getting annoyed by a pop-up everytime a perception roll is done.

You could add a system-specific workaround, like how for example, in PF2e you need to use the Seek action to detect secret tokens and doors. If such prerequisite is met somewhere in the roll data, the roll will create the pop-up by default.

**Comment by Saibot393** [comment]
I have just released v1.5.2 which adds a setting Force invert "Ignore Roll" key that inverts the key for all players, i think thats the best middle ground to solve both problems

**Comment by Saibot393** [comment]
I have added an optional GM dialog for spotting with v1.6.0
