### ISSUE TITLE
Bizarre issue with inconsistently appearing Perceptive tag on token settings

### ISSUE THREAD

**Issue by GaistH** [Saibot393/perceptive#80]
This is a really bizarre and probably niche issue but it's got me absolutely stumped: I am using latest versions of Foundry (v11.315), Perceptive (v3.3.3) and the PF1E system (v9.6).  I have two different worlds on the same local Foundry server instance, sharing the same modules directory / copy of Perceptive, using the same modules overall -- and in particular, both have identical settings under System Settings for Perceptive.

Despite this, in one of the worlds, the Perceptive tab for token settings always appears, whether I have only Perceptive enabled by itself, or with any combination of modules up to all of the modules being enabled -- it's basically bulletproof that it always shows up.  In the other world, the Perceptive tab for token settings _never_ appears, whether I have only Perceptive enabled by itself or with any combination of modules up to all of the modules being enabled.

It's baffling and I can't figure it out, I've tried Find the Culprit dozens of times, I've gone back and forth comparing the settings over and over again and I just can't make heads or tails of it and I'm stumped as to where else I could even begin to try to troubleshoot it.  If you have any suggestions, I would greatly appreciate it!

**Comment by Saibot393** [comment]
This sounds quite strange indeed. The only way i can see to fix this is, if you send me the world files (without the media files) of both worlds so i can take a closer look. If you prefer you can send the files via a discord DM (saibot5279)
