### ISSUE TITLE
[Feature Request] Option to have minimum perception DC as -4 for DnD 5e.

### ISSUE THREAD

**Issue by Dukezilent** [Saibot393/perceptive#85]
As of now, 0 is the absolute minimum value you can have for both perception DCs. However, the theoretical min you can have for a stealth check is -4 (With a Dex score of 1, you have Dex mod. of -5. Upon rolling a 1 on a d20, you get the net value of -4). Though I acknowledge the fact that this is limited to few use cases, there is plenty of other creatures with Dex mod. of less than or equal to -2 (ex. zombie) which would allow them to get a net negative.

**Comment by Saibot393** [comment]
The problem with that is, that perceptive uses -1 as a replacement for infinity/an impossible DC. Adding negative numbers as valid DC would mean that:
a) another value has to be used for infinity (which may cause confusion/problems)
b) perceptive would have to go through all tokens, tiles and doors to set (should they have a negative DC) the value to the new infinity value (which is possible but may take a while)

So, the work and confusion it may cause on my side and for users is a bit high, compared to the potential usefulness in my opinion

**Comment by Dukezilent** [comment]
Yeah that's understandable. For now, I will manually set the DC to 0 if it were to happen during my games. Thanks for considering it though!

**Comment by Saibot393** [comment]
i will however add something, that stealth results below zero are set to 0

**Comment by Saibot393** [comment]
With v3.5.5 stealth results below 0 will now be set to 0
