### ISSUE TITLE
[Bug] Cannot Read Properties

### ISSUE THREAD

**Issue by Travinkel** [Saibot393/perceptive#86]
Hi. I am getting the error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'effects')
    at PerceptiveCompUtils.FilterDFEffects (PerceptiveCompUtils.js:164:81)
    at EffectManager.applyStealthEffects (EffectManager.js:73:44)

![image](https://github.com/Saibot393/perceptive/assets/57225948/e4306bae-0bcf-4a24-8e3f-423fd66264ae)

**Comment by Saibot393** [comment]
Did this ever come up again after the update?
