### ISSUE TITLE
[BUG] Spot Range is infinite range for Passive DC.

### ISSUE THREAD

**Issue by InstantZzz** [Saibot393/perceptive#87]
Hello.

I recently tried your module after watching a Baileywiki video about your module.
I copied his instruction from the video but have come to issue I've mention in the title - Passive perception checks have infinite range.
I assume (based on his video) that when setting Spotting Range is uses the game defined ranges, in my case D&D 5E.

I have left everything to default with the main concern being the "Maximum interaction distance" as I assume this relates to Spotting Range but more likely is for peeking.
The only feature I have changed is that I toggled ON "activate spot invisible feature". Activate Vision Channels seems related but frankly, I do not understand how that works and have left it toggled OFF.

As for my testing, I created a new game and only enabled this module. I then created an invisible door and place it at one end of the map. My map is 8x6 or 40ft by 30ft. I then enable "Can be spotted" and "reveal when spotted" and then I set the Passive Perception DC to 12 and the Spot Range to 5. I create a new Actor and set his Passive Perception to 12. I place the token on far end of the map, opposite the hidden door. I move my token 5ft (1 square) closer and the door is revealed even though it is more than 30ft away.

I did not mention above but I created a Plater account on my game and assigned the Actor to them for testing.
GAME INFO: Foundry v11.315, D&D 5E v3.1.1

**Comment by Saibot393** [comment]
The spotting range is a separate setting found under Spot Invisible settings>Sight Range>Spotting range, you will also need to turn the range on changing the setting Apply range (found under the previous setting) to watever suits your usecase.
Ragarding the Vision Channels feature:
It basically allows you to set objects as emitting on certain channels and tokens as receiving certain channels. If those match and based on the matching channels settings, this could allow for certain things: Seing the object in another color, seing the object through walls, only seeing the object when the channels match, being able to completly see through certain walls or being able to walk through certain walls

**Comment by InstantZzz** [comment]
> The spotting range is a separate setting found under Spot Invisible settings>Sight Range>Spotting range, you will also need to turn the range on changing the setting Apply range (found under the previous setting) to watever suits your usecase. Ragarding the Vision Channels feature: It basically allows you to set objects as emitting on certain channels and tokens as receiving certain channels. If those match and based on the matching channels settings, this could allow for certain things: Seing the object in another color, seing the object through walls, only seeing the object when the channels match, being able to completly see through certain walls or being able to walk through certain walls

Okay, I had a hard time understanding what you meant until I saw "Sight Range" with an arrow next to it. I didn't realize that those were drop-down menus.

Thanks.
