### ISSUE TITLE
Stealthy 4.0.1 has new interface to set stealth values

### ISSUE THREAD

**Issue by Eligarf** [Saibot393/perceptive#88]
Since Stealthy 4.x.x now stores stealth values in either the token or actor depending on the GMs choice, I've updated the API functions to insulate other modules from those internals. Instead of directly setting the values in the hidden effect, you should call `stealthy.bankStealth(token, value)` so it gets routed appropriately. Similarly, `stealthy.bankPerception(token, value)` will handle setting perception values. `stealthy.getBankedStealth(token)` and `stealthy.getBankedPerception(token)` are the reader functions.

**Comment by Saibot393** [comment]
Thank you, i will look into changing that as soon as possible

**Comment by Saibot393** [comment]
I tried using the `stealthy.bankStealth(token, value)` to set the stealth value of a token, there seems to be something missing in the code:
![image](https://github.com/Saibot393/perceptive/assets/137942782/5f6e4dd8-6784-46fb-b7cc-df6a8c2fabfc)

**Comment by Eligarf** [comment]
Dumb transcription error on my part, the internal call was misnamed. Fixing now, will have 4.0.5 out in a few minutes

**Comment by Eligarf** [comment]
Just tested this up on forge and it works as it should. You can grab it directly or update via normal means: [Stealthy v4.0.4](https://github.com/Eligarf/stealthy/releases/download/v4.0.4/module.json)

**Comment by Saibot393** [comment]
Thank you, i will release the compatibility update shortly

**Comment by Eligarf** [comment]
I appreciate the compatibility support. Perceptive seems to be everything Stealthy would want to be should it grow up :smile:

**Comment by Saibot393** [comment]
So, the compatibility should be restored with perceptive v3.5.8.
I sometimes fear that the features included in perceptive grew a bit to fast, especially at the beginning. There are one or two features that do not work quite as stable as i would want them to work, due to the basic code never being written with them in mind. But oh well, they work for now.
