### ISSUE TITLE
Typo in DFreds compat

### ISSUE THREAD

**Issue by txm3278** [Saibot393/perceptive#9]
https://github.com/Saibot393/perceptive/blob/1e54ca14b795fc3b566f97e8d112aa1760d9d782/scripts/compatibility/PerceptiveCompUtils.js#L121C7-L121C7

Also I can't seem to get names to work in the settings, the id throws this error.

**Comment by Saibot393** [comment]
I already have a fix for that in another module, will take a few hours so until i can update it.

**Comment by Saibot393** [comment]
I have just released v1.5.3 which should fix this bug
