### ISSUE TITLE
Modifying token fields like disposition or scale leads to creation of Hidden state with Stealthy integration.

### ISSUE THREAD

**Issue by Eligarf** [Saibot393/perceptive#92]
Just a heads up that you might have some unexpected behavior happening in Perceptive. Over in Stealthy-land, I've had a couple of users report Hidden effects being spontaneously generated when editing seemingly unrelated token values when Stealthy Integration is enabled in Perceptive. One reported it when changing a token's disposition from hostile to friendly, and another reported it when editing token scale or light radius [Stealthy issue #132](https://github.com/Eligarf/stealthy/issues/132). As far as I can tell, these Hidden states are being created because Stealthy is receiving a `bankStealth` command from Perceptive; the issue goes away if 'Stealthy Integration' is disabled, as Stealthy itself only adds a Hidden state if either a Stealth roll is made or a call to `stealthy.bankStealth` is made (which Stealthy doesn't use internally).

**Comment by Saibot393** [comment]
Thanks for the heads up. Could you add an optional parameter to `stealthy.bankStealth` so that it can be called to update the stealth value without actuallly applying the stealth effect?

**Comment by Eligarf** [comment]
The GM has a setting that controls whether the stealth value is banked in the actor or token, so I follow that. I'm curious, why do you want to bank a stealth value without causing a token to become hidden? This is certainly surprising behavior to someone who is changing a token disposition; if I understood the intent perhaps I can adjust things to be more in line.

**Comment by Saibot393** [comment]
Maybe i am missunderstanding the purpose of banking. In perceptive a GM can set the stealth value/DC and then later make the token invisible (effectively apply the set value) e.g. by adding an invisibility effect.

**Comment by Saibot393** [comment]
Ah, ok. I guess the simplest solution would then be for me to check if a token actually has a banked stealth before banking the new value. Is there a function to check that in the api?

**Comment by Eligarf** [comment]
`getBankedStealth`

**Comment by Saibot393** [comment]
The behavious should now be fixed with v3.6.1

**Comment by Eligarf** [comment]
Thank you very much!
