### ISSUE TITLE
Global Stealth Settings

### ISSUE THREAD

**Issue by VirusNik21** [Saibot393/perceptive#98]
I studied the entire module and built it for myself - great job. 
There is one last question left:
Where is this settings on a token setup?
1) Stealth effects[Tokens only]: to add additional stealth effects to this token
2) Override world stealth effects[Tokens only]: to override the worlds stealth effects with this tokens custom stealth effects
![Token](https://github.com/Saibot393/perceptive/assets/150345729/c66ba000-1af8-4860-bfe8-2e313f2da179)

**Comment by Saibot393** [comment]
Those settings are only available if [DFreds Convenient Effects](https://foundryvtt.com/packages/dfreds-convenient-effects) is installed and the integration (world setting "DFreds Convenient Effects Integration") is enabled. The Module is not yet compatible with v12 from what it seems, in case you are using that version.

**Comment by VirusNik21** [comment]
Thanks, and yes. I'm using V12.
