### ISSUE TITLE
Language pt-BR.

### ISSUE THREAD

**Issue by Andersants** [Saibot393/perceptive#99]
Hello, your module is great.
I've made a translation to pt-BR for version 3.5.10.
If you have any lines that are different from the current version, if you let me know I can inform you of the translation to be added.

[pt-BR.json](https://github.com/user-attachments/files/15810628/pt-BR.json)

**Comment by Saibot393** [comment]
Thank you very much for the translation, i have included it with v4.0.7.
I am really sorry that this took so long, the issue somehow slipped my inbox.
